-- Drop the PETRESCUE table in case it exists
drop table PETRESCUE;
-- Create the PETRESCUE table 
create table PETRESCUE (
	ID INTEGER NOT NULL,
	ANIMAL VARCHAR(20),
	QUANTITY INTEGER,
	COST DECIMAL(6,2),
	RESCUEDATE DATE,
	PRIMARY KEY (ID)
	);
-- Insert sample data into PETRESCUE table
insert into PETRESCUE values 
	(1,'Cat',9,450.09,'2018-05-29'),
	(2,'Dog',3,666.66,'2018-06-01'),
	(3,'Dog',1,100.00,'2018-06-04'),
	(4,'Parrot',2,50.00,'2018-06-04'),
	(5,'Dog',1,75.75,'2018-06-10'),
	(6,'Hamster',6,60.60,'2018-06-11'),
	(7,'Cat',1,44.44,'2018-06-11'),
	(8,'Goldfish',24,48.48,'2018-06-14'),
	(9,'Dog',2,222.22,'2018-06-15')

-- Return the table
SELECT * FROM PETRESCUE;

-- QA1:
SELECT SUM(cost) FROM PETRESCUE;

-- QA2:
SELECT SUM(cost) AS SUM_OF_COST FROM PETRESCUE;

-- QA3: 
SELECT MAX(quantity) FROM PETRESCUE;

--Alternative solving:
SELECT animal, SUM(quantity) AS quantity FROM PETRESCUE
GROUP BY animal
ORDER BY quantity DESC
LIMIT 1;

-- QA4:
SELECT AVG(cost) FROM PETRESCUE;

-- QA5:
SELECT AVG(COST/QUANTITY) FROM PETRESCUE 
WHERE ANIMAL = 'Dog';


-- QB1:
SELECT animal,ROUND(cost) FROM PETRESCUE;

-- QB2:
SELECT LENGTH(animal) FROM PETRESCUE;

-- QB3:
SELECT UPPER(animal) FROM PETRESCUE

-- QB4:
SELECT DISTINCT(UPPER(animal)) FROM PETRESCUE;

-- QB5:
SELECT * FROM PETRESCUE
WHERE LOWER(animal) = 'cat';

-- QC1:
SELECT DAY(rescuedate) FROM PETRESCUE 
WHERE ANIMAL = 'Cat';

-- QC2:
SELECT SUM(quantity) FROM PETRESCUE 
WHERE MONTH(RESCUEDATE) = '05';

-- QC3:
SELECT SUM(quantity) FROM PETRESCUE
WHERE DAY(rescuedate) = '14';

-- QC4:
SELECT(rescuedate + 3 DAYS) FROM PETRESCUE

-- QC5:
SELECT(CURRENT DATE - rescuedate) FROM PETRESCUE
